### ISSUE TITLE
微服务demo，本地build，docker部署到本地后有一些问题

### ISSUE THREAD

**Issue by likai3615560** [cnAbp/abp#27]
1：访问后端管理应用程序（BackendAdminApp.Host）:( http://localhost:51512 用于管理系统中的用户和产品，跳转到授权登陆页面，注册ok，然后跳转不回来，重新打开后跳到http://localhost:51512/Account/AccessDenied?ReturnUrl=%2FIdentity%2FUsers 无法访问
2.public web site  点击  blog模块，动不动就超时，限流了吗？
3.代码看了一下没找到问题，想先跑起来看看效果再学习代码，有人遇到过这种问题吗
4.这个demo 吃磁盘吗？之前docker在c盘部署，一直100%使用率，根本无法访问，后来换到d盘正常了，有时候也会跳到60~80%

**Comment by E2Home** [comment]
没有在docker中尝试过，目前只是看看里面打代码结构。
